### PR TITLE
[LG 14519] Change Dev Docs language from Dashboard to Portal

### PR DESCRIPTION
**Pull request by rahul-kamarouthu**
[LG 14519] Change Dev Docs language from Dashboard to Portal

Jira ticket - https://cm-jira.usa.gov/browse/LG-14519

### CODE REVIEW

**Review by ajfarkas — CHANGES_REQUESTED** [review]
One instance of "Dashboard" in `_pages/overview.md`. I'm not entirely sure that the text is correct, since the link is to IDP and will not redirect the partner to the Portal.

But this does raise the question of whether you should update the URL from `dashboard.int.identitysandbox.gov` to `portal.int.identitysandbox.gov`, especially where that address is displayed in text (on `_pages/testing.md`)

Screenshot 2024-11-07 at 3 39 33 PM

**Comment by rahul-kamarouthu** [comment]
> One instance of "Dashboard" in `_pages/overview.md`. I'm not entirely sure that the text is correct, since the link is to IDP and will not redirect the partner to the Portal.
> 
> But this does raise the question of whether you should update the URL from `dashboard.int.identitysandbox.gov` to `portal.int.identitysandbox.gov`, especially where that address is displayed in text (on `_pages/testing.md`)
> 
> Screenshot 2024-11-07 at 3 39 33 PM

Changed!

**Comment by ajfarkas** [comment]
The issue remains that the last link you updated is incorrect: it does not take the user to the Partner Portal.

I also think it's worth checking whether we should be updating the URL here, so that users are not hovering over "Partner Portal" and seeing `https://dashboard.int.identitysandbox.gov`.

**Review by ajfarkas — APPROVED** [review]
Let's get this moving.
Please make sure we have a ticket to update the remaining URL's to the `portal` subdomain.

**Pull request merged**
